[package]
name = "tz-wrapped-backend"
version = "0.1.0"
authors = ["Mike Godenzi <m.godenzi@papers.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
sodiumoxide = "0.2.6"
