[server]
address = "0.0.0.0:80"
inactivity_timeout_seconds = 1800

[database]
host = "postgres"
port = "5432"
user = "user"
password = "password"
name = "tz-wrapped"

[smtp]
host = ""
port = "587"
user = ""
password = ""
