[tezos]
node_url = "https://testnet-tezos.giganode.io"

[[contracts]]
address = "KT192P1oDzf3fNb7BSEiC1d74KvQf4HrivBE"
multisig = "KT1WHkRut4W4jCjarMG77brvjvD6WN96arYg"
name = "tzBTC"
kind = "fa1"
token_id = 0
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push GK"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"
name = "Picnic Give"
email = "godenzim@me.com"

[[contracts.keyholders]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.keyholders]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"

[[contracts.keyholders]]
public_key = "edpkuwf84xZoEpu88JgprPcee4CZsj5iXzs77M65CxmQd6qqZFBNSJ"
name = "Idea Obscure"
email = "godenzim@me.com"

[[contracts]]
address = "KT1CzBckMYTXnY4tdZqoGpjxpyaiU7EwxW2J"
multisig = "KT1E8ZCP3NuL5TTnqkZL5oK9nMqSKrob4MWQ"
name = "tzETH"
kind = "fa2"
token_id = 0
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkvKgKWxh5m2G1qBn4HS1VN3bF63D723Ba9eKacdSPCBzLWe1WCy"
name = "Original Cluster"
email = "godenzim@me.com"

[[contracts.keyholders]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "mike@hypergate.com"

[[contracts.keyholders]]
public_key = "edpkv6MFhAVnpAhrvMjdW1tGfLDDiU6i6P9kt3ZmyiiMpxCsB5Cg4v"
name = "Thrive Umbrella"
email = "godenzim@me.com"

[[contracts.keyholders]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"
