[[server.admins]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"

[[tezos_nodes]]
name = "Papers"
url = "https://tezos-hangzhounet-node.prod.gke.papers.tech"
network = "hangzhounet"

[[tezos_nodes]]
name = "SmartPy"
url = "https://hangzhounet.smartpy.io"
network = "hangzhounet"

[[tezos_nodes]]
name = "Cryptonomic"
url = "https://tezos-hangzhou.cryptonomic-infra.tech"
network = "hangzhounet"

[[contracts]]
address = "KT1PCjoT2Z1oz1Vr5Nb1QHTTBYc1sLrbuoig"
decimals = 8
kind = "fa1"
multisig = "KT19LDmB7UV7q4vpvcnRrh3sHogFrXWwTXrt"
name = "tzBTC - Owner"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"

[[contracts]]
address = "KT1PCjoT2Z1oz1Vr5Nb1QHTTBYc1sLrbuoig"
decimals = 8
kind = "fa1"
multisig = "KT1V5jtRwSqPXRVj3GKK6WG4YuomufrpkjdY"
name = "tzBTC - Operator"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

[[contracts.gatekeepers]]
public_key = "edpktrFtPi9VkDMJdxb7jqNLAm279sEDx9v22hWGtVoZYAsMWYypdk"

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
