[tezos]
node_url = "https://delphinet-tezos.giganode.io"

[[contracts]]
address = "KT1Q66HBBQYaHGAKnxeuedkgLyJYF9jkD96H"
multisig = "KT1BYMvJoM75JyqFbsLKouqkAv8dgEvViioP"
name = "tzBTC"
kind = "fa1"
token_id = 0
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkvVL8vEq7PTm7mbTyomvA3h6RNsJTKt213WN2Z4Zt87cQommPZ3"
name = "Tester"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Bitcoin Suisse"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "inacta"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Lexr"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Swiss Crypto Tokens"
email = "godenzim@me.com"

[[contracts]]
address = "KT1S4QXjASmM3ei7a6raRLkr4TbnKu7RuC9X"
multisig = "KT1TD6buzFQbLLYfx92UpZ6N2jfCaat3GSrN"
name = "tzETH"
kind = "fa2"
token_id = 0
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Alice"
email = "mike@hypergate.com"

[[contracts.keyholders]]
name = "Robert"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Dan"
email = "godenzim@me.com"
