[tezos]
node_url = "https://testnet-tezos.giganode.io"

[[contracts]]
address = "KT192P1oDzf3fNb7BSEiC1d74KvQf4HrivBE"
multisig = "KT1WHkRut4W4jCjarMG77brvjvD6WN96arYg"
name = "tzBTC"
kind = "fa1"
token_id = 0
symbol = "tzBTC"
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkuM1Y5MQcBsiZqj9Lf5KhLKrZY2egsenoY7W1B4ppWUMCGVJAYJ"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

[[contracts]]
address = "KT1CzBckMYTXnY4tdZqoGpjxpyaiU7EwxW2J"
multisig = "KT1E8ZCP3NuL5TTnqkZL5oK9nMqSKrob4MWQ"
name = "tzETH"
kind = "fa2"
token_id = 0
symbol = "tzETH"
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkuM1Y5MQcBsiZqj9Lf5KhLKrZY2egsenoY7W1B4ppWUMCGVJAYJ"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"
