[tezos]
node_url = "https://testnet-tezos.giganode.io"

[[contracts]]
address = "KT1X6iAsssYNMK4YQC7ujvfAHiwqdwbac73Q"
multisig = "KT1BAxSLXenicfoNAA6EXe8RojVpBJ3KiMCt"
name = "tzBTC"
kind = "fa1"
token_id = 0
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkvVL8vEq7PTm7mbTyomvA3h6RNsJTKt213WN2Z4Zt87cQommPZ3"
name = "Tester"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Bitcoin Suisse"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"
name = "Picnic Give"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "inacta"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Lexr"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Swiss Crypto Tokens"
email = "godenzim@me.com"

[[contracts]]
address = "KT1R9zSv54P6H4okbLQYKA6S8W3zdsKR6cTJ"
multisig = "KT1LW1vW2XhQ2VA5xfG3cpLVVetadi65QYbP"
name = "tzETH"
kind = "fa2"
token_id = 0
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkvKgKWxh5m2G1qBn4HS1VN3bF63D723Ba9eKacdSPCBzLWe1WCy"
name = "Original Cluster"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Alice"
email = "mike@hypergate.com"

[[contracts.keyholders]]
name = "Robert"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Dan"
email = "godenzim@me.com"
