[server]
address = "0.0.0.0:8080"
domain_name = "localhost"

[[server.admins]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"

[[tezos_nodes]]
name = "Papers"
url = "https://tezos-hangzhounet-node.prod.gke.papers.tech"
network = "hangzhounet"

[[tezos_nodes]]
name = "SmartPy"
url = "https://hangzhounet.smartpy.io"
network = "hangzhounet"

[[tezos_nodes]]
name = "Cryptonomic"
url = "https://tezos-hangzhou.cryptonomic-infra.tech"
network = "hangzhounet"

[database]
host = "localhost"

# Contract config for tzBTC Owner
[[contracts]]
address = "KT1P5PYmFTcCfAUF8N5mP77rZUS7Ji7gpjcC" # address of the contract
decimals = 8 
kind = "fa1" # this can either be fa1 or fa2
multisig = "KT19LDmB7UV7q4vpvcnRrh3sHogFrXWwTXrt" # address of the multisig contract used to interact with the contract
name = "tzBTC - Owner" # The name displayed in the frontend dropdown menu
symbol = "tzBTC" 
token_id = 0 # this value is not important if the kind value is fa1

[[contracts.capabilities]]
operation_request_kind = "update_keyholders" # what the multisig contract can do, valid values are: update_keyholders, mint, burn

# The list of gatekeepers public keys
[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

# Contract config for tzBTC Operator
[[contracts]]
address = "KT1P5PYmFTcCfAUF8N5mP77rZUS7Ji7gpjcC"
decimals = 8
kind = "fa1"
multisig = "KT1V5jtRwSqPXRVj3GKK6WG4YuomufrpkjdY"
name = "tzBTC - Operator"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
