[server]
domain_name = "localhost"

[tezos]
node_url = "https://testnet-tezos.giganode.io"

[database]
host = "localhost"

[[contracts]]
address = "KT1Q66HBBQYaHGAKnxeuedkgLyJYF9jkD96H"
multisig = "KT1BYMvJoM75JyqFbsLKouqkAv8dgEvViioP"
name = "tzBTC"
kind = "fa1"
token_id = 0
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push GK"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"
name = "Picnic Give"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Thrive Umbrella"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Sudden Push KH"
email = "godenzim@me.com"

[[contracts]]
address = "KT1R9zSv54P6H4okbLQYKA6S8W3zdsKR6cTJ"
multisig = "KT1LW1vW2XhQ2VA5xfG3cpLVVetadi65QYbP"
name = "tzETH"
kind = "fa2"
token_id = 0
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "godenzim@me.com"

[[contracts.gatekeepers]]
public_key = "edpkvKgKWxh5m2G1qBn4HS1VN3bF63D723Ba9eKacdSPCBzLWe1WCy"
name = "Original Cluster"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Alice"
email = "mike@hypergate.com"

[[contracts.keyholders]]
name = "Robert"
email = "godenzim@me.com"

[[contracts.keyholders]]
name = "Dan"
email = "godenzim@me.com"
