[tezos]
node_url = "https://delphinet-tezos.giganode.io"

[database]
host = "localhost"

[[contracts]]
address = "KT1Q66HBBQYaHGAKnxeuedkgLyJYF9jkD96H"
multisig = "KT1BYMvJoM75JyqFbsLKouqkAv8dgEvViioP"
name = "tzBTC"
kind = "fa1"
token_id = 0
decimals = 8

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "m.godenzi@papers.ch"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push GK"
email = "m.godenzi@papers.ch"

[[contracts.keyholders]]
name = "Ugly Release"
email = "mike@hypergate.com"

[[contracts.keyholders]]
name = "Thrive Umbrella"
email = "m.godenzi@papers.ch"

[[contracts.keyholders]]
name = "Sudden Push KH"
email = "m.godenzi@papers.ch"

[[contracts]]
address = "KT1S4QXjASmM3ei7a6raRLkr4TbnKu7RuC9X"
multisig = "KT1TD6buzFQbLLYfx92UpZ6N2jfCaat3GSrN"
name = "tzETH"
kind = "fa2"
token_id = 0
decimals = 18

[[contracts.gatekeepers]]
public_key = "edpkumVGEtDQgDAcMyB5FRn7UBLuhzg6D7aEnCDamXgjqGxavnsgvP"
name = "Ugly Release"
email = "m.godenzi@papers.ch"

[[contracts.gatekeepers]]
public_key = "edpktwdcwT8iMDWcg2ePJ6J1sbwXYdn7GYJWyRybi8vpkrv4aduFHt"
name = "Sudden Push"
email = "m.godenzi@papers.ch"

[[contracts.keyholders]]
name = "Alice"
email = "mike@hypergate.com"

[[contracts.keyholders]]
name = "Robert"
email = "m.godenzi@papers.ch"

[[contracts.keyholders]]
name = "Dan"
email = "m.godenzi@papers.ch"
