[server]
domain_name = "localhost"

[tezos]
node_url = "https://testnet-tezos.giganode.io"

[database]
host = "localhost"

[[contracts]]
address = "KT192P1oDzf3fNb7BSEiC1d74KvQf4HrivBE"
multisig = "KT1KiJ1N9wgEVGkgPDYhLBYRBMPy1RG3pN2J"
name = "tzBTC - Owner"
kind = "fa1"
token_id = 0
symbol = "tzBTC"
decimals = 8

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

[[contracts]]
address = "KT192P1oDzf3fNb7BSEiC1d74KvQf4HrivBE"
multisig = "KT1WHkRut4W4jCjarMG77brvjvD6WN96arYg"
name = "tzBTC - Operator"
kind = "fa1"
token_id = 0
symbol = "tzBTC"
decimals = 8

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

[[contracts.gatekeepers]]
public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

[[contracts.gatekeepers]]
public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"

# [[contracts]]
# address = "KT1CzBckMYTXnY4tdZqoGpjxpyaiU7EwxW2J"
# multisig = "KT1E8ZCP3NuL5TTnqkZL5oK9nMqSKrob4MWQ"
# name = "tzETH"
# kind = "fa2"
# token_id = 0
# symbol = "tzETH"
# decimals = 18

# [[contracts.gatekeepers]]
# public_key = "edpkuHG9N83cBavucaLSeeKX3AVjn9wDyFeFmrhaSLqvmBycP5N7Zs"

# [[contracts.gatekeepers]]
# public_key = "edpktfkToequZjyn3jz3GJobiYApkc5q4xnJiksStYbZkznUdsxDUw"

# [[contracts.gatekeepers]]
# public_key = "edpktgVTATaPnXTLUV88RmGKVF5GA12QXH1GKPpCcn56htnGpQbk2b"
