[[server.admins]]
public_key = "edpktrFtPi9VkDMJdxb7jqNLAm279sEDx9v22hWGtVoZYAsMWYypdk"

[[server.admins]]
public_key = "edpktvdiC9azpXNLiZ9WpF7ZYao4gzhmMJmARuQW2xPyqUrmnbjx7X"

[[tezos_nodes]]
name = "Papers"
url = "https://tezos-node.prod.gke.papers.tech"
network = "mainnet"

[[tezos_nodes]]
name = "SmartPy"
url = "https://mainnet.smartpy.io/"
network = "mainnet"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
decimals = 8
kind = "fa1"
multisig = "KT1QeoDkCAdJSSnm7zWz6Nv7W82qaoUz7kC9"
name = "tzBTC - Owner"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "add_operator"

[[contracts.capabilities]]
operation_request_kind = "remove_operator"

[[contracts.capabilities]]
operation_request_kind = "set_redeem_address"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkur75zYgZauFuFAP5hBNtjSXH2agcsUT91GJZKT7mx1zuCV2CEK"

[[contracts.gatekeepers]]
public_key = "edpktfv1MJjNkvLXWHqUshyq2y7yKjvH9RNBKLCgKNbSkonhPbjYsC"

[[contracts.gatekeepers]]
public_key = "edpkvWKVSXH5HD6ky8ZMaiVQQKC91FyoY7NTpgK2aqia5bRBvXnsPF"

[[contracts.gatekeepers]]
public_key = "edpkuBMxCHKtG2SUeNbucqs7PzYZtQKT9WJGcQVVPbbe4RLJjBk8zF"

[[contracts.gatekeepers]]
public_key = "edpktrFtPi9VkDMJdxb7jqNLAm279sEDx9v22hWGtVoZYAsMWYypdk"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
decimals = 8
kind = "fa1"
multisig = "KT1FcmdSroia1ys1WM6mL2rzB1haLxyy3MH9"
name = "tzBTC - Operator"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkv7S5kYHd7qqMnCt12fCKZpsr24jRAXiEJxxN9TWqufDGxFKYAJ"

[[contracts.gatekeepers]]
public_key = "edpkuDrjKhzfRpgfFMgrvZosGWTmMSVerTq7WGNvQZNayHWGRqzYcc"

[[contracts.gatekeepers]]
public_key = "edpku5KnvR4eyPVhmqoNv9uY8BvcSu8Pq4YtdYcAM11YhGCRADEypw"

[[contracts.gatekeepers]]
public_key = "edpkuG9moBtUHgSzbkLcpUzCdSgiE6r9YjQu3dQU3AtuCPvHbJbFNi"

[[contracts.gatekeepers]]
public_key = "edpktrFtPi9VkDMJdxb7jqNLAm279sEDx9v22hWGtVoZYAsMWYypdk"

[[contracts.gatekeepers]]
public_key = "edpkuhvWerUKKkE7cAafLhmpkW5mAnXBk1wxwMpoBsoqpHqdhBw6Ex"

[[contracts.gatekeepers]]
public_key = "edpkuRZepzeDzSsJEHTSPc5CkWySwai4LTYn7EaFbjmvx6xnwafTKJ"

[[contracts.gatekeepers]]
public_key = "edpktvdiC9azpXNLiZ9WpF7ZYao4gzhmMJmARuQW2xPyqUrmnbjx7X"

