[tezos]
node_url = "https://mainnet-tezos.giganode.io"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
multisig = "KT1QeoDkCAdJSSnm7zWz6Nv7W82qaoUz7kC9"
name = "tzBTC - Owner"
kind = "fa1"
token_id = 0
symbol = "tzBTC"
decimals = 8

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuhvWerUKKkE7cAafLhmpkW5mAnXBk1wxwMpoBsoqpHqdhBw6Ex"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
multisig = "KT1FcmdSroia1ys1WM6mL2rzB1haLxyy3MH9"
name = "tzBTC - Operator"
kind = "fa1"
token_id = 0
symbol = "tzBTC"
decimals = 8

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuhvWerUKKkE7cAafLhmpkW5mAnXBk1wxwMpoBsoqpHqdhBw6Ex"

[[contracts.gatekeepers]]
public_key = "edpkuRZepzeDzSsJEHTSPc5CkWySwai4LTYn7EaFbjmvx6xnwafTKJ"

[[contracts.gatekeepers]]
public_key = "edpkv8vx9bkSY24EEV2LsfW3ZKavoma5CcvdQCqg6UUokPqxsPQ6BZ"
