[[tezos_nodes]]
name = "Papers"
url = "https://tezos-node.prod.gke.papers.tech"
network = "mainnet"

[[tezos_nodes]]
name = "SmartPy"
url = "https://mainnet.smartpy.io/"
network = "mainnet"

[[tezos_nodes]]
name = "Cryptonomic"
url = "https://tezos-prod.cryptonomic-infra.tech"
network = "mainnet"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
decimals = 8
kind = "fa1"
multisig = "KT1QeoDkCAdJSSnm7zWz6Nv7W82qaoUz7kC9"
name = "tzBTC - Owner"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuhvWerUKKkE7cAafLhmpkW5mAnXBk1wxwMpoBsoqpHqdhBw6Ex"

[[contracts]]
address = "KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn"
decimals = 8
kind = "fa1"
multisig = "KT1V5jtRwSqPXRVj3GKK6WG4YuomufrpkjdY"
name = "tzBTC - Operator"
symbol = "tzBTC"
token_id = 0

[[contracts.capabilities]]
operation_request_kind = "mint"

[[contracts.capabilities]]
operation_request_kind = "burn"

[[contracts.capabilities]]
operation_request_kind = "update_keyholders"

[[contracts.gatekeepers]]
public_key = "edpkuhvWerUKKkE7cAafLhmpkW5mAnXBk1wxwMpoBsoqpHqdhBw6Ex"

[[contracts.gatekeepers]]
public_key = "edpkuRZepzeDzSsJEHTSPc5CkWySwai4LTYn7EaFbjmvx6xnwafTKJ"

[[contracts.gatekeepers]]
public_key = "edpkv8vx9bkSY24EEV2LsfW3ZKavoma5CcvdQCqg6UUokPqxsPQ6BZ"

[[contracts.gatekeepers]]
public_key = "edpktrFtPi9VkDMJdxb7jqNLAm279sEDx9v22hWGtVoZYAsMWYypdk"
